services:
  - type: web
    name: emugradproject-api
    env: python
    buildCommand: pip install -r plagcheck/requirements.txt
    startCommand: gunicorn --chdir plagcheck app:app
    envVars:
      - key: CORS_ORIGIN
        value: https://tolgaosman.github.io
