services:
  - type: web
    name: emugradproject-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend --timeout 120 app:app
    envVars:
      - key: CORS_ORIGIN
        value: https://tolgaosman.github.io
