import type { AIScore } from '../api/types'

interface AIDetectionResultsProps {
  scores: AIScore[]
}

export function AIDetectionResults({ scores }: AIDetectionResultsProps) {
  if (!scores || scores.length === 0) {
    return (
      <div className="empty-state">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
        <p>No AI detection results available.</p>
      </div>
    )
  }

  // Sort by probability descending
  const sortedScores = [...scores].sort((a, b) => b.overall_probability - a.overall_probability)
  const bandToColor = { low: 'low', possible: 'medium', likely: 'high' } as const

  return (
    <div className="ai-results-container">
      <h3>AI Detection Report</h3>
      <p className="ai-description">
        This panel estimates the probability that the uploaded files were generated by an AI model
        (like ChatGPT or GitHub Copilot). Higher percentages indicate stronger AI signals. This is a
        fully offline heuristic, not a trained classifier — treat every result as indicative, not
        conclusive, and never as evidence of misconduct on its own.
      </p>

      <div className="ai-scores-list">
        {sortedScores.map((score, idx) => {
          const percentage = Math.round(score.overall_probability * 100)
          const colorClass = bandToColor[score.band]

          return (
            <div key={idx} className={`ai-score-card ${colorClass}`}>
              <div className="ai-score-header">
                <span className="file-name">{score.file}</span>
                <span className={`percentage-badge ${colorClass}`}>{percentage}% AI</span>
              </div>
              <div className="progress-bar-bg">
                <div 
                  className={`progress-bar-fill ${colorClass}`}
                  style={{ width: `${percentage}%` }}
                ></div>
              </div>
            </div>
          )
        })}
      </div>

      <style>{`
        .ai-results-container {
          background: var(--surface);
          border: 1px solid var(--border);
          border-radius: 12px;
          padding: 1.5rem;
          margin-top: 1rem;
          box-shadow: 0 1px 3px rgba(0,0,0,0.02);
        }
        .ai-results-container h3 {
          margin: 0 0 0.5rem 0;
          font-size: 1.25rem;
          font-weight: 600;
          letter-spacing: -0.01em;
        }
        .ai-description {
          color: var(--text-muted);
          font-size: 0.95rem;
          margin: 0 0 1.5rem 0;
        }
        .ai-scores-list {
          display: flex;
          flex-direction: column;
          gap: 1rem;
        }
        .ai-score-card {
          border: 1px solid var(--border);
          border-radius: 8px;
          padding: 1rem;
          background: var(--bg);
        }
        .ai-score-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 0.75rem;
        }
        .file-name {
          font-weight: 500;
          font-size: 0.95rem;
          font-family: var(--font-mono, monospace);
        }
        .percentage-badge {
          font-weight: 600;
          font-size: 0.85rem;
          padding: 0.25rem 0.5rem;
          border-radius: 9999px;
        }
        .percentage-badge.low { background: var(--emerald-bg, #ecfdf5); color: var(--emerald, #059669); }
        .percentage-badge.medium { background: var(--amber-bg); color: var(--amber); }
        .percentage-badge.high { background: var(--red-bg); color: var(--red); }
        
        .progress-bar-bg {
          height: 8px;
          background: var(--border);
          border-radius: 9999px;
          overflow: hidden;
        }
        .progress-bar-fill {
          height: 100%;
          border-radius: 9999px;
          transition: width 0.5s ease-out;
        }
        .progress-bar-fill.low { background: var(--emerald, #059669); }
        .progress-bar-fill.medium { background: var(--amber); }
        .progress-bar-fill.high { background: var(--red); }
      `}</style>
    </div>
  )
}
