import { useEffect, useState } from 'react'
import type { AIScore } from '../api/types'
import { CodePane } from './CodePane'

interface AIDetectionResultsProps {
  scores: AIScore[]
  files: File[]
}

const bandToColor = { low: 'low', possible: 'medium', likely: 'high' } as const
const bandToLabel = { low: 'Low', possible: 'Possible', likely: 'Likely' } as const

function SignalBars({ signals }: { signals: AIScore['signals'] }) {
  if (signals.length === 0) return null
  return (
    <div className="ai-signals">
      {signals.map((signal) => (
        <div key={signal.name} className="ai-signal-row">
          <span className="ai-signal-name">{signal.name.replace(/_/g, ' ')}</span>
          <div className="progress-bar-bg ai-signal-bar-bg">
            <div className="progress-bar-fill medium" style={{ width: `${Math.round(signal.score * 100)}%` }} />
          </div>
          <span className="ai-signal-value">{signal.score.toFixed(2)}</span>
        </div>
      ))}
    </div>
  )
}

function DocumentViewer({ file, score }: { file: File | undefined; score: AIScore }) {
  const [text, setText] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false
    if (!file) {
      setText(null)
      return
    }
    file
      .text()
      .then((t) => {
        if (!cancelled) setText(t)
      })
      .catch(() => {
        if (!cancelled) setText(null)
      })
    return () => {
      cancelled = true
    }
  }, [file])

  if (!text) return null

  const spans = score.segments
    .filter((s) => s.probability >= 0.5)
    .map((s) => ({ start: s.start, end: s.end }))

  return <CodePane text={text} spans={spans} />
}

export function AIDetectionResults({ scores, files }: AIDetectionResultsProps) {
  if (!scores || scores.length === 0) {
    return (
      <div className="empty-state">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
        <p>No AI detection results available.</p>
      </div>
    )
  }

  const sortedScores = [...scores].sort((a, b) => b.overall_probability - a.overall_probability)

  return (
    <div className="ai-results-container">
      <p className="ai-description">
        This panel estimates the probability that the uploaded files were generated by an AI model
        (like ChatGPT or GitHub Copilot). Higher percentages indicate stronger AI signals. This is a
        fully offline heuristic, not a trained classifier — treat every result as indicative, not
        conclusive, and never as evidence of misconduct on its own.
      </p>

      {sortedScores.map((score) => {
        const percentage = Math.round(score.overall_probability * 100)
        const colorClass = bandToColor[score.band]
        const file = files.find((f) => f.name === score.file)

        return (
          <div key={score.file} className="card ai-score-card">
            <div className="card-head">
              <span className="file-name">{score.file}</span>
              <span className={`badge-chip ${colorClass}`}>
                {bandToLabel[score.band]} · {percentage}%
              </span>
            </div>
            <div className="progress-bar-bg">
              <div className={`progress-bar-fill ${colorClass}`} style={{ width: `${percentage}%` }} />
            </div>

            <SignalBars signals={score.signals} />
            <DocumentViewer file={file} score={score} />
          </div>
        )
      })}
    </div>
  )
}
